### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by azaroth42** [duraspace/pcdm#10]
Following from discussion at and around OR2015, there has been confusion and disagreement around exactly how ordering should be specified.

The proposal is as follows:
- If there is no order, then no problem :)
- The first (likely only) and primary order is associated with the proxies of the Object or Collection.
- Secondary and subsequent orders are associated with the proxies of a second Object.

The reasoning:
- Consistency for multiple orders (always requiring a second Object) is a high cost, for a _very_ small number of use cases. Making the simple postcard case harder for the sake of consistency with rebound medieval manuscripts is not the way we want to go.
- We do not know of a use case for multiple orders for a single Collection. Requiring an Object to assert the only order of a Collection would be ... very strange.
- The use of Object is to allow all of the other affordances of the class -- relatedObjects, files and relatedFiles.  For example to attach justification or rationale for the second order, a filmstrip thumbnail that summarizes the order, and so forth.
- The relationship between the main Object and the one that establishes order is (at least) pcdm:hasRelatedObject.

The outstanding issues:
- Should there be a pcdm:Order subclass of pcdm:Object?
- Should there be a pcdm:orderedBy subproperty of pcdm:hasRelatedObject?
- Should there be both?

Single Order model:
![order-5](https://cloud.githubusercontent.com/assets/871868/8189192/713aefdc-140f-11e5-9aa1-901406b76243.png)

Multiple Orders model:
![order-two-1](https://cloud.githubusercontent.com/assets/871868/8189236/c207429e-140f-11e5-9cf7-fc6f2c4a0feb.png)

**Comment by elrayle** [comment]
My memory of the conversation is a little different.  In order to maintain flexibility for potential use cases, pcdm:order was going to be on par with pcdm:object and pcdm:collection and have the following behaviors defined.

See gist https://gist.github.com/elrayle/409e4a773e49d9a15b12 for the proposed implementation.

**Comment by azaroth42** [comment]
Sorry Lynette, but that doesn't allow for orders to have files or related objects which is a requirement.

**Comment by elrayle** [comment]
The list of behaviors in the comments shows related files and related objects.  I missed adding the code for related files, but the code is there for related objects.  See indirectly_contains :related_objects at line 30.

**Comment by elrayle** [comment]
I updated the code to include related files at line 38.  Related objects shifted to line 33 since I added comments that make it easier to find where the relationships are defined in the code.

**Comment by azaroth42** [comment]
Oh, ore:aggregates rather than pcdm:hasRelatedObject ... but the hasFile still stands.  If an Object hasFile a pdf representation of that "thing", then an Order Object should also be able to hasFile a pdf with a different ordering of the contents. (Which was in-person discussion at OR, as opposed to email)

**Comment by elrayle** [comment]
By defining pcdm:order without the restrictive rules of pcdm:object, this will allow for future use cases requiring multiple orders for collections and still meet the current use cases for multiple orders for objects.

**Comment by elrayle** [comment]
Can you expand upon that use case Rob?  It is not intuitive to me for an order to have a primary file, as opposed to a related file.  An order in my mind should do one thing, order items.

BTW, the switch to use pcdm:hasRelatedObject has been discussed, but the code has not been implemented.  I was copying from existing code to create the gist.

**Comment by azaroth42** [comment]
I have a book that has 2 orders of the same 10 pages.  I can associate a PDF with the book, with the primary ordering of the pages.  That is done with book hasFile pdf.  Unless orders can have files, there isn't a way to provide a PDF of the second order.  Or, a thumbnail filmstrip image rather than a PDF.

Otherwise I would need to have a related Object to hold the thumbnail ... and then I don't need an Order object, I can just express the second order with the Object... which is the proposal :)

Unless there's a use case for multiply ordered collections, the discussion was that we don't need to address it.  No one could come up with an even hypothetical one, let alone one that was shared. If you have one, that would be great to discuss

**Comment by escowles** [comment]
This all lines up with my memory of the discussions -- including not being able to come up with a use case for collections being ordered, much less multiply-ordered.

Having a pcdm:Order subclass lines up better with the file use vocabulary approach, but I'm fine with an pcdm:orderedBy property, or both.

**Comment by azaroth42** [comment]
And from me:
+1 to   pcdm:Order rdfs:subClassOf pcdm:Object
+0 to also having   pcdm:orderedBy rdfs:subPropertyOf pcdm:hasRelatedObject

**Comment by elrayle** [comment]
For clarity, can you state the behaviors of a pcdm:order and how it is different from a pcdm:object.  For example...

a pcdm:order has all the behaviors of an object with the following limitations...

Option 1:
- a pcdm:order's members are all the members of the parent pcdm:object
- adding a member to the parent pcdm:object automatically adds (appends?) that member to its pcdm:orders

Option 2:
- a pcdm:order's members is a subset of the members of the parent pcdm:object
- adding a member to the parent pcdm:object does not add it to pcdm:orders for that object

Option 3:
- there are no limits to the members of the pcdm:orders

**Comment by jpstroop** [comment]
I don't see a reason for orderedBy.

**Comment by escowles** [comment]
-1 to option 1: leaving items out is one way two orderings could be different
+1 to option 2: this is what I was thinking of
+0 to option 3: maybe there's a use case for including additional members?  On a practical level, it seems challenging to enforce anyway.

**Comment by elrayle** [comment]
I don’t mean to drag this out, but I am having a difficult time seeing the need for additional infrastructure in Fedora to support multi-orders.  The way order behaviors are currently defined in the proposal can be implemented at the pcdm level with some minor changes to pcdm:object and adding pcdm:order which includes all pcdm:object behaviors and any new behaviors of orders.

See gist… https://gist.github.com/elrayle/e5eba35a623909488ee1

Note:
- line 14 adds an indirect_container to hold orders in pcdm:object  (This is indirect only because I copied the code for related objects.  I’m not sure why related objects container was implemented with indirect instead of direct or basic containers.)
- line 28 & 29 includes both object and order behaviors in pcdm:order
- line 41 & 44 prevent orders from having orders
- line 47 I wan’t able to think of any new behaviors for pcdm:order
- line 54 and below show a few services for pcdm:order.  These would be needed regardless of an implementation at the pcdm level or at the Fedora level
  *\*  line 56 CreateOrder
  *\*  line 70 AddObjectToOrder
  *\*  line 89 GetOrdersFromObject

In the proposal, the following changes were to be made at the Fedora level…
- Fedora has a sub-directory named /orders which will hold the proxies for alternate orders

Questions/Observations:
-  Is there a benefit to the end user having /orders in Fedora vs. defining a container to hold orders at the pcdm level?
-  Adding /orders to Fedora adds extra code and complexity to be maintained.  The modifications to the pcdm level will have the same scale and complexity whether orders are implemented with Fedora /orders or at the pcdm level only.
- Am I missing some of the benefits that support making the changes at the Fedora level?

**Comment by escowles** [comment]
Since pcdm:Order as proposed is a subclass of pcdm:Object, and we're using the pcdm:hasRelatedObject to link to it, I think it's fine to just put the additional orders with the other related objects.  Since there isn't a different predicate to manage, the orders/ container wouldn't really help us.

**Comment by elrayle** [comment]
Perhaps I misunderstood.  I thought that https://github.com/duraspace/pcdm/issues/11 was proposing additional work at the Fedora level.

Esme, are you suggesting that non-order related objects and orders be maintained in the same container?

**Comment by escowles** [comment]
@elrayle Yes, I'm saying I'm not sure what functionality is gained by #11:
- We can use pcdm:hasRelatedObject to link to them, so the separate container isn't needed to manage a different relationship.
- The pcdm:Order behavior is essentially the same as pcdm:Object (the type just indicates it exists to hold an order), so they can coexist in the same container.

**Comment by elrayle** [comment]
What kinds of queries do you want to make with orders?

For example...
- all_pcdm_orders = GetAllOrders( parent_object )
- pcdm_order = GetOrderByURI( parent_object, order_uri )

**Comment by azaroth42** [comment]
_If_ there is an orderedBy relationship, then the direct /orders/ container
would be able to manage that directly.
If there's only a class, then it wouldn't make any difference at a model
level.

At a structural level, an Order is tied pretty closely to its parent
Object, though the membership isn't necessarily identical.  One wouldn't
want to repeat all of the base metadata for the order, for example.  So the
thought was that it could be below the main object rather than a
sibling.... thus #11.

**Comment by tpendragon** [comment]
This has been languishing a while, and there's been some comments about it lately, so can we move towards getting this closed?

My understanding is the following:

> Should there be a pcdm:Order subclass of pcdm:Object?

Yes

> Should there be a pcdm:orderedBy subproperty of pcdm:hasRelatedObject?

No

> Should there be both?

No

Yes? If so, maybe it's time for a PR?

**Comment by escowles** [comment]
:+1: -- that's my understanding of the consensus we've reached.

**Comment by azaroth42** [comment]
I think this issue can be closed, no?

**Comment by escowles** [comment]
+1 to closing

**Comment by elrayle** [comment]
I'm ok with closing.
