### ISSUE TITLE
External "File"s?

### ISSUE THREAD

**Issue by azaroth42** [duraspace/pcdm#21]
I want to have the equivalent of a pcdm:File, but not maintain it in the repository.  Instead it is maintained by an external system, such as a IIIF Image server. Use case:  Building out the structure of an object in PCDM, but keeping the image content elsewhere.  I may still want to have technical, rights or other metadata about the external "File".

So I guess the question is ... can a pcdm:File have zero bitstreams, or is a bitstream a requirement?
In Fedora4/LDP, there must be some NonRdfSource to hang the fcr:metadata off...

**Comment by escowles** [comment]
The Fedora 4 REST API provides a mechanism to create a 0-byte NonRDFSource, which redirects to a URL specified in the headers when you create it:

https://wiki.duraspace.org/display/FEDORA4x/RESTful+HTTP+API+-+Containers#RESTfulHTTPAPI-Containers-external-content

So that would provide a NonRDFSource to hang the metadata off of, and allows you to redirect to the URL on the external system instead of having the content in the repository.

**Comment by awoods** [comment]
:+1: @escowles

**Comment by scossu** [comment]
:+1: @azaroth42 and @escowles This is a very useful feature.

**Comment by ruthtillman** [comment]
++ing this because it was one reason our institution adopted Fedora vs
others, this flexibility. We don't own everything we manage--it'd be great
if we did, but we don't, so we have to handle that use case.

**Comment by azaroth42** [comment]
:+1: Should we document this somewhere for PCDM?

**Comment by awoods** [comment]
An update to the wiki makes sense:
https://github.com/duraspace/pcdm/wiki

**Comment by escowles** [comment]
I've added a note to the File section mentioning Files with no content and Fedora's external content feature:

https://github.com/duraspace/pcdm/wiki#user-content-external-content

**Comment by awoods** [comment]
Thanks, @escowles. Please feel free to close this issue if you are satisfied, @azaroth42.

**Comment by azaroth42** [comment]
Closed, thanks for the proposal and update @escowles!
