### ISSUE TITLE
Clarify non-requirement of LDP in PCDM 2.0

### ISSUE THREAD

**Issue by awead** [duraspace/pcdm#56]
If I understand correctly, PCDM does not require LDP containment. Could this be clarified in 2.0? Under Files, I'm seeing

> Files MUST be contained by exactly one FileSet.

I think we mean here that a File object can be the member of only one FileSet.

**Comment by awead** [comment]
Direct containment makes sense in this case, so maybe we need to clarify _which_ classes use LDP and which don't, but it's basically just all predicates, right? So it's up to the implementor to choose how they want to manage them.

**Comment by escowles** [comment]
@awead I agree, it would be better to change that language to avoid "contained" which implied LDP concepts that are not required.  Though I'm also hesitant to use "member" either, since that's a different concept too.

How about "The cardinality of pcdm:hasFile is 1-to-many: an Object can have many Files, and a File can be a fileOf a single Object." ?

**Comment by awead** [comment]
@escowles works for me! How about another statement about LDP specifically? Ex, "While LDP can be used in an implementation of PCDM, it is not required. It can be used to manage the predicates that are required for PCDM."

**Comment by escowles** [comment]
OK, I've update the PCDM 2.0 wiki page.
